#!/bin/bash
export LINUX_GIT="git@github.com:MeticulousHome/linux-fika.git"
export LINUX_BRANCH="stable"
export HISTORY_UI_REV="452f6984333304c914554bf4470d42721a8e696c" # fix(config): conditionally set assetPrefix in Next.js config
export LINUX_REV="HEAD" # Merge pull request #2 from MeticulousHome/nightly
export UBOOT_BRANCH="stable"
export UBOOT_REV="HEAD" # config:_Enable GPIO read command
export ATF_REV="bed39c167c883b335d5fc1046ce16e10a611b4c4" # plat: imx8m: Fix compile errors with active VAR_ENABLE_IMX_UART
export IMX_MKIMAGE_REV="71b8c18af93a5eb972d80fbec290006066cff24f" # Add flash_all_ap target for non-Linux ap image.
export DEBIAN_BRANCH="stable"
export DEBIAN_REV="HEAD" # nxp: remove last bin of NXP / variscite specific firmware
export BACKEND_BRANCH="stable"
export BACKEND_REV="HEAD" # Merge pull request #352 from MeticulousHome/nightly
export DIAL_BRANCH="disable-fluent-bit"
export DIAL_REV="ce062dacc39da751f540969dd4fcff714130867f" # Remove Fluent Bit setting from Dial
export WEB_APP_BRANCH="stable"
export WEB_APP_REV="HEAD" # Merge pull request #4 from MeticulousHome/nightly
export WATCHER_BRANCH="stable"
export WATCHER_REV="HEAD" # Merge pull request #9 from MeticulousHome/nightly
export FIRMWARE_BRANCH="stable"
export FIRMWARE_REV="HEAD" # Merge pull request #484 from MeticulousHome/nightly
export RAUC_BRANCH="stable"
export RAUC_REV="HEAD" # debian: Disable test building for now
export HAWKBIT_BRANCH="stable"
export HAWKBIT_REV="HEAD" # fix: Take into account partial download size
export PSPLASH_BRANCH="stable"
export PSPLASH_REV="HEAD" # Replace baseimage with DOT image
export PLOTTER_UI_BRANCH="stable"
export PLOTTER_UI_REV="HEAD" # Merge pull request #30 from MeticulousHome/nightly
export CRASH_REPORTER_BRANCH="stable"
export CRASH_REPORTER_REV="HEAD" # run cargo fmt
