name: Build image

on:
  schedule:
    - cron: '0 0 * * *'  # Nightly at midnight
  workflow_dispatch:  # Allows manual triggering
    inputs:
      image:
        description: Which image to build
        default: nightly

permissions:
  contents: read
  actions: read
  id-token: write

run-name: "Build ${{github.event.inputs.image || 'default (nightly)' }} image"

jobs:
  build-components:
    name: Build all image components
    secrets: inherit
    uses: meticuloushome/meticulous-machine/.github/workflows/build-all-components.yml@set_up_pcb_tester_uptodate
    with:
      image: ${{ inputs['image'] || 'nightly' }}

  build-root:
    name: Build RootFS
    runs-on: ubuntu-24.04
    needs: 
      - build-components
    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 6000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git authentication
      run: |
        git config --global url."https://${{ secrets.GH_REPO_WORKFLOW }}@github.com/".insteadOf "git@github.com:"

    - name: Download bootloader artifact
      uses: actions/download-artifact@v4
      with:
        name: 'bootloader'
        path: components/bootloader/build/

    - name: Download linux artifact
      uses: actions/download-artifact@v4
      with:
        name: 'linux'
        path: components/linux-build

    - name: Download debian artifact
      uses: actions/download-artifact@v4
      with:
        name: 'debian'
        path: components/debian-base/

    - name: Download crash reporter artifact
      uses: actions/download-artifact@v4
      with:
        name: 'crash-reporter'
        path: components/crash-reporter/target

    - name: Download psplash artifact
      uses: actions/download-artifact@v4
      with:
        name: 'psplash'
        path: components/psplash-build

    - name: Download rauc artifact
      uses: actions/download-artifact@v4
      with:
        name: 'rauc'
        path:  components/rauc/build

    - name: Download web artifact
      uses: actions/download-artifact@v4
      with:
        name: 'web'
        path:  components/meticulous-web-ui/out/

    - name: Download firmware artifact
      uses: actions/download-artifact@v4
      with:
        name: 'firmware'
        path:  components/meticulous-firmware-build

    - name: Download plotter artifact
      uses: actions/download-artifact@v4
      with:
        name: 'plotter'
        path:  components/meticulous-plotter-ui/build/


    - name: Install Ubuntu dependencies
      run: ./update-sources.sh --install_ubuntu_dependencies

    - name: Install qemu-img
      run: |
        sudo apt install -y qemu-utils qemu-user-static

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: 'Exporting pio'
      run: echo "/home/runner/.platformio/penv/bin" >> $GITHUB_PATH

    - name: Checkout all the python sources
      run: ./update-sources.sh  --backend --watcher --image ${{ inputs['image'] || 'nightly' }}

    - name: Write build channel to image-build-channel
      run: |
        echo "${{ inputs.image || 'nightly' }}" | sudo tee ./image-build-channel > /dev/null

    - name: Generate repository information
      run: |
        ./generate_repo_info.sh

    - name: Build rootfs
      run: |
        sudo ./make-rootfs.sh --all
        sudo cat rootfs/opt/summary.txt | sed 's/ ##$//g' >> $GITHUB_STEP_SUMMARY

    - name: Delete original debian rootfs
      run: rm -r ./components/debian-base/rootfs-base.tar.gz

    - name: Upload rootfs artifact
      uses: actions/upload-artifact@v4
      with:
        name: meticulous-rootfs.tar.gz
        path: meticulous-rootfs.tar.gz
        if-no-files-found: error

    - name: Build sdcard
      run: sudo ./make-sdcard.sh --image

    - name: Upload SDCard artifact
      uses: actions/upload-artifact@v4
      with:
        name: sdcard.img
        path: sdcard.img
        if-no-files-found: error

    - name: Upload EMMC artifact
      uses: actions/upload-artifact@v4
      with:
        name: emmc.img
        path: emmc.img
        if-no-files-found: error