name: Build nightly sdcard image

on:
  schedule:
    - cron: '0 0 * * *'  # Nightly at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-upload:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: rootfs
        github-token: ${{ secrets.GH_TOKEN }}
        path: ./debian/output/rootfs.tar.gz

    - name: Set up Git authentication
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "git@github.com:"

    - name: Install Ubuntu dependencies
      run: ./update-sources.sh --install_ubuntu_dependencies

    - name: Downgrade qemu-user-static
      run: |
        sudo apt install -y --allow-downgrades ./misc/qemu-user-static_8.0.4+dfsg-1ubuntu5_amd64.deb
        sudo apt-mark hold qemu-user-static

    - name: Checkout all the sources
      run: ./update-sources.sh --all --firmware

    - name: Build components
      run: ./build-components.sh --dial --dash --web --firmware

    - name: Build components
      run: sudo ./make-rootfs.sh --all

    - name: Build sdcard
      run: sudo ./make-sdcard.sh --image

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sdcard
        path: sdcard.img.gz
