name: Build nightly sdcard image

on:
  schedule:
    - cron: '0 0 * * *'  # Nightly at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-sdcard-and-upload:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git authentication
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "git@github.com:"

    - name: Get latest debian workflow run ID
      id: get_run_id
      run: |
        latest_run_id=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-debian-base.yml/runs?status=success&per_page=1" \
          | jq -r '.workflow_runs[0].id')
        echo "latest_run_id=${latest_run_id}" >> $GITHUB_ENV

    - name: Download debian artifact
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ env.latest_run_id }}
        name: rootfs
        github-token: ${{ secrets.GH_TOKEN }}
        path: ./components/debian/output

    - name: Install Ubuntu dependencies
      run: ./update-sources.sh --install_ubuntu_dependencies

    - name: Downgrade qemu-user-static
      run: |
        sudo apt install -y --allow-downgrades ./misc/qemu-user-static_8.0.4+dfsg-1ubuntu5_amd64.deb
        sudo apt-mark hold qemu-user-static

    - name: 'Exporting pio'
      run: echo "/home/runner/.platformio/penv/bin" >> $GITHUB_PATH

    - name: Checkout all the sources
      run: ./update-sources.sh --backend --watcher --dial  --web --firmware

    - name: Build components
      run: ./build-components.sh --dial --web --firmware

    - name: Build rootfs
      run: sudo ./make-rootfs.sh --all

    - name: Build sdcard
      run: sudo ./make-sdcard.sh --image

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sdcard
        path: |
          sdcard.img.gz
          emmc.img.gz
