name: Build nightly images

on:
  schedule:
    - cron: '0 0 * * *'  # Nightly at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-root:
    runs-on: ubuntu-24.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 6000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git authentication
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "git@github.com:"

    - name: Get latest debian workflow run ID
      id: get_run_id
      run: |
        latest_run_id=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-debian-base.yml/runs?status=success&per_page=1" \
          | jq -r '.workflow_runs[0].id')
        echo "latest_run_id=${latest_run_id}" >> $GITHUB_ENV

    - name: Download debian artifact
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ env.latest_run_id }}
        name: rootfs
        github-token: ${{ secrets.GH_TOKEN }}
        path: ./components/debian/output

    - name: Install Ubuntu dependencies
      run: ./update-sources.sh --install_ubuntu_dependencies

    - name: Downgrade qemu-user-static
      run: |
        sudo apt install -y --allow-downgrades ./misc/qemu-user-static_8.0.4+dfsg-1ubuntu5_amd64.deb
        sudo apt-mark hold qemu-user-static

    - name: Install qemu-img
      run: |
        sudo apt install -y qemu-utils

    - name: 'Exporting pio'
      run: echo "/home/runner/.platformio/penv/bin" >> $GITHUB_PATH

    - name: Checkout all the sources
      run: ./update-sources.sh --backend --watcher --dial  --web --firmware

    - name: Build components
      run: ./build-components.sh --dial --web --firmware

    - name: Build rootfs
      run: sudo ./make-rootfs.sh --all

    - name: Delete original debian rootfs
      run: rm -r ./components/debian/output/rootfs*

    - name: Upload rootfs artifact
      uses: actions/upload-artifact@v4
      with:
        name: rootfs
        path: meticulous-rootfs.tar.gz
        if-no-files-found: error

    - name: Build sdcard
      run: sudo ./make-sdcard.sh --image

    - name: Upload SDCard artifact
      uses: actions/upload-artifact@v4
      with:
        name: sdcard
        path: sdcard.img.gz
        if-no-files-found: error

    - name: Upload EMMC artifact
      uses: actions/upload-artifact@v4
      with:
        name: emmc
        path: emmc.img.gz
        if-no-files-found: error

  build-bundle:
    needs: build-root
    runs-on: ubuntu-24.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 6000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git authentication
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "git@github.com:"

    - name: Download rootfs artifact
      uses: actions/download-artifact@v4
      with:
        name: rootfs
        path: meticulous-rootfs.tar.gz

    - name: Clone private repository
      uses: actions/checkout@v4
      with:
        repository: MeticulousHome/rauc-secrets
        token: ${{ secrets.GH_TOKEN }}
        path: /tmp/rauc-secrets

    - name: Install Ubuntu dependencies
      run: ./update-sources.sh --install_ubuntu_dependencies

    - name: Downgrade qemu-user-static
      run: |
        sudo apt install -y --allow-downgrades ./misc/qemu-user-static_8.0.4+dfsg-1ubuntu5_amd64.deb
        sudo apt-mark hold qemu-user-static

    - name: Install qemu-img
      run: |
        sudo apt install -y qemu-utils

    - name: Build Bundles
      run: ./make-ota.sh  --nightly --cert /tmp/rauc-secrets/keys/beta.rsa4096.cert.pem --key /tmp/rauc-secrets/keys/beta.rsa4096.key.pem

    - name: Upload SDCard bundle
      uses: actions/upload-artifact@v4
      with:
        name: sdcard-bundle
        path: rauc_meticulous_sdcard_*.raucb
        if-no-files-found: error

    - name: Upload EMMC bundle
      uses: actions/upload-artifact@v4
      with:
        name: emmc
        path: rauc_meticulous_emmc_*.raucb
        if-no-files-found: error
