name: Build rauc and rauc-hawkbit-updater

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-rauc:
    runs-on: ubuntu-24.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 6000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get latest meticulous image workflow run ID
      id: get_run_id
      run: |
        latest_run_id=$(curl -s \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-nightly-image.yml/runs?status=success&per_page=1" \
          | jq -r '.workflow_runs[0].id')
        echo "latest_run_id=${latest_run_id}" >> $GITHUB_ENV
        echo "latest_run_id=${latest_run_id}"

    - name: Download debian artifact
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ env.latest_run_id }}
        name: 'rootfs.tar.gz'
        github-token: ${{ secrets.GH_TOKEN }}
        path: .

    - name: Install Ubuntu dependencies
      run: sudo apt update && sudo apt install -y systemd-container qemu-utils pv jq wget tar sed

    - name: Downgrade qemu-user-static
      run: |
        sudo apt install -y --allow-downgrades ./misc/qemu-user-static_8.0.4+dfsg-1ubuntu5_amd64.deb
        sudo apt-mark hold qemu-user-static

    - name: Build python
      run: sudo ./misc/build-rauc.sh

    - name: Upload python artifact
      uses: actions/upload-artifact@v4
      with:
        name: python
        path: |
          misc/rauc*.deb
          misc/rauc-hawkbit-updater*.deb
        if-no-files-found: error

