name: Upload bundle to hawkbit

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  upload-bundle:
    # needs: build-bundle
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests attrs 

    - name: Get latest debian workflow run ID
      id: get_run_id
      run: |
        latest_run_id=$(curl -s \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-nightly-image.yml/runs?status=success&per_page=1" \
          | jq -r '.workflow_runs[0].id')
        echo "latest_run_id=${latest_run_id}" >> $GITHUB_ENV

    - name: Download sdcard bundle
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ env.latest_run_id }}
        name: sdcard-bundle
        github-token: ${{ secrets.GH_TOKEN }}
        path: .

    - name: Download emmc bundle
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ env.latest_run_id }}
        name: sdcard-bundle
        github-token: ${{ secrets.GH_TOKEN }}
        path: .
    
    - name: Upload sdcard bundle
      run: |
        python misc/upload-bundle.py *_sdcard_*.raucb ${{ secrets.HAWKBIT_USER }}  ${{ secrets.HAWKBIT_PASSWORD }} rootfs-sdcard "nightly-$(date)"

    - name: Upload emmc bundle
      run: |
        python misc/upload-bundle.py *_emmc_*.raucb  ${{ secrets.HAWKBIT_USER }}  ${{ secrets.HAWKBIT_PASSWORD }}rootfs-emmc "nightly-$(date)"
